image:
  repository: drumsergio/genieacs
  pullPolicy: IfNotPresent
  tag: "1.2"

service_http:
  type: ClusterIP
  port_http: 3000
service_cwmp:
  type: ClusterIP
  port_cwmp: 7547
service_nbi:
  type: ClusterIP
  port_nbi: 7557
service_fs:
  type: ClusterIP
  port_fs: 7567

ingress:
  enabled: true
  className: "" #Use the ingress controller of your cluster
  annotations: # If it is nginx-based... {}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: # Modify according to your size
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi